### ISSUE TITLE
Add codequest_pipes to travis-ci

### ISSUE THREAD

**Issue by grodowski** [codequest-eu/codequest_pipes#1]
It would be really cool to see a Travis badge inside the readme and test against multiple Rubies.

**Comment by marcinwyszynski** [comment]
![jesus-says-meme-generator-jesus-says-go-4-it-0e2ac3](https://cloud.githubusercontent.com/assets/571786/10770568/44c2b890-7cec-11e5-94a1-8b4e11ab6f7a.jpg)
